version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_qrcode
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=qrcode
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=VGKE4CtwcSjkgdD
      - MYSQL_ADDRESS=10.9.103.123:3306
networks:
  default:
    external:
      name: wxcb0
